services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pismo-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    restart: unless-stopped
