-- PostgreSQL Schema for Production
-- This file is only used with PostgreSQL (prod profile)
-- For H2 (dev profile), schema is auto-generated by Hibernate

-- Create accounts table
CREATE TABLE IF NOT EXISTS accounts (
    account_id BIGSERIAL PRIMARY KEY,
    document_number VARCHAR(14) NOT NULL UNIQUE
);

-- Create operation_types table
CREATE TABLE IF NOT EXISTS operation_types (
    operation_type_id BIGINT PRIMARY KEY,
    description VARCHAR(50) NOT NULL
);

-- Create transactions table
CREATE TABLE IF NOT EXISTS transactions (
    transaction_id BIGSERIAL PRIMARY KEY,
    account_id BIGINT NOT NULL,
    operation_type_id BIGINT NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    event_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES accounts(account_id),
    CONSTRAINT fk_operation_type FOREIGN KEY (operation_type_id) REFERENCES operation_types(operation_type_id)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON transactions(account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_operation_type_id ON transactions(operation_type_id);
CREATE INDEX IF NOT EXISTS idx_transactions_event_date ON transactions(event_date);
CREATE INDEX IF NOT EXISTS idx_accounts_document_number ON accounts(document_number);
